// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/warehouse/service.proto

package warehouse

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetOrdersReq struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrdersReq) Reset()         { *m = GetOrdersReq{} }
func (m *GetOrdersReq) String() string { return proto.CompactTextString(m) }
func (*GetOrdersReq) ProtoMessage()    {}
func (*GetOrdersReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_331f9124fc90f6ac, []int{0}
}
func (m *GetOrdersReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrdersReq.Unmarshal(m, b)
}
func (m *GetOrdersReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrdersReq.Marshal(b, m, deterministic)
}
func (dst *GetOrdersReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrdersReq.Merge(dst, src)
}
func (m *GetOrdersReq) XXX_Size() int {
	return xxx_messageInfo_GetOrdersReq.Size(m)
}
func (m *GetOrdersReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrdersReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrdersReq proto.InternalMessageInfo

func (m *GetOrdersReq) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetOrdersResp struct {
	Orders               []*Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrdersResp) Reset()         { *m = GetOrdersResp{} }
func (m *GetOrdersResp) String() string { return proto.CompactTextString(m) }
func (*GetOrdersResp) ProtoMessage()    {}
func (*GetOrdersResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_331f9124fc90f6ac, []int{1}
}
func (m *GetOrdersResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrdersResp.Unmarshal(m, b)
}
func (m *GetOrdersResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrdersResp.Marshal(b, m, deterministic)
}
func (dst *GetOrdersResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrdersResp.Merge(dst, src)
}
func (m *GetOrdersResp) XXX_Size() int {
	return xxx_messageInfo_GetOrdersResp.Size(m)
}
func (m *GetOrdersResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrdersResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrdersResp proto.InternalMessageInfo

func (m *GetOrdersResp) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

type Order struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_331f9124fc90f6ac, []int{2}
}
func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (dst *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(dst, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Order) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Order) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*GetOrdersReq)(nil), "twirp.gowroc.warehouse.GetOrdersReq")
	proto.RegisterType((*GetOrdersResp)(nil), "twirp.gowroc.warehouse.GetOrdersResp")
	proto.RegisterType((*Order)(nil), "twirp.gowroc.warehouse.Order")
}

func init() {
	proto.RegisterFile("rpc/warehouse/service.proto", fileDescriptor_service_331f9124fc90f6ac)
}

var fileDescriptor_service_331f9124fc90f6ac = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0x2a, 0x48, 0xd6,
	0x2f, 0x4f, 0x2c, 0x4a, 0xcd, 0xc8, 0x2f, 0x2d, 0x4e, 0xd5, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c,
	0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x2b, 0x29, 0xcf, 0x2c, 0x2a, 0xd0, 0x4b,
	0xcf, 0x2f, 0x2f, 0xca, 0x4f, 0xd6, 0x83, 0xab, 0x52, 0x52, 0xe3, 0xe2, 0x71, 0x4f, 0x2d, 0xf1,
	0x2f, 0x4a, 0x49, 0x2d, 0x2a, 0x0e, 0x4a, 0x2d, 0x14, 0x12, 0xe3, 0x62, 0x2b, 0x2e, 0x49, 0x2c,
	0x29, 0x2d, 0x96, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf2, 0x94, 0xdc, 0xb8, 0x78, 0x91,
	0xd4, 0x15, 0x17, 0x08, 0x99, 0x72, 0xb1, 0xe5, 0x83, 0x79, 0x12, 0x8c, 0x0a, 0xcc, 0x1a, 0xdc,
	0x46, 0xb2, 0x7a, 0xd8, 0x6d, 0xd0, 0x03, 0xeb, 0x09, 0x82, 0x2a, 0x56, 0x72, 0xe6, 0x62, 0x05,
	0x0b, 0x08, 0xf1, 0x71, 0x31, 0x65, 0xa6, 0x80, 0x2d, 0x61, 0x0d, 0x62, 0xca, 0x4c, 0x11, 0x12,
	0xe2, 0x62, 0x29, 0xa9, 0x2c, 0x48, 0x95, 0x60, 0x02, 0x5b, 0x0b, 0x66, 0x23, 0x39, 0x86, 0x19,
	0xd9, 0x31, 0x46, 0xa9, 0x5c, 0x9c, 0xe1, 0x30, 0xf3, 0x85, 0x22, 0xb8, 0x38, 0xe1, 0x2e, 0x13,
	0x52, 0xc1, 0xe5, 0x0a, 0x64, 0x4f, 0x4a, 0xa9, 0x12, 0xa1, 0xaa, 0xb8, 0xc0, 0x89, 0x3b, 0x8a,
	0x13, 0x2e, 0x95, 0xc4, 0x06, 0x0e, 0x47, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xaa, 0xcb,
	0xd7, 0x85, 0x66, 0x01, 0x00, 0x00,
}
